import {
  getStoredCustomLanguages,
  inspectStoredCustomLanguages,
  normalizeLanguageIdentity,
} from "./customLanguages";
import {
  commitTranslationTransaction,
  createTranslationTransactionPlan,
  readRawTranslationSnapshot,
  translationStorageKeys,
  type TranslationStorage,
} from "./translationStorage";

export type LanguageCode = string;

export type SupportedLanguage = {
  code: string;
  label: string;
  nativeLabel: string;
};

export const languageStorageKey = translationStorageKeys.selectedLanguage;
export const defaultLanguageCode: LanguageCode = "en";

const builtInLanguages: SupportedLanguage[] = [
  { code: "en", label: "English", nativeLabel: "English" },
];

export { builtInLanguages };

function browserStorage(): TranslationStorage | null {
  return typeof window === "undefined" ? null : window.localStorage;
}

export function getSupportedLanguages(
  storage: TranslationStorage | null = browserStorage(),
): SupportedLanguage[] {
  if (!storage) return [...builtInLanguages];

  const custom: SupportedLanguage[] = getStoredCustomLanguages(storage).map(
    (language) => ({
      code: normalizeLanguageIdentity(language.code)!,
      label: language.label,
      nativeLabel: language.label,
    }),
  );
  return [...builtInLanguages, ...custom];
}

/** @deprecated Use getSupportedLanguages() for dynamic list */
export const supportedLanguages = builtInLanguages;

type TranslationDictionary = Partial<Record<string, string>>;

const englishDictionary: TranslationDictionary = {
  // Sidebar
  "app.sidebar.subtitle": "Private local catalog",
  "app.sidebar.expand": "Expand sidebar",
  "app.sidebar.collapse": "Collapse sidebar",
  "app.sidebar.navigateTo": "Navigate to {label}",
  "nav.home": "Home",
  "nav.videos": "Videos",
  "nav.images": "Images",
  "nav.performers": "Performers",
  "nav.categories": "Categories",
  "nav.glossary": "Glossary",
  "nav.settings": "Settings",

  // Settings
  "settings.title": "Settings",
  "settings.description":
    "Manage application preferences, optimization, data safety, and app information.",
  "settings.resetToDefaults": "Reset to Defaults",
  "settings.appearance.title": "Appearance",
  "settings.appearance.description": "Customize how Sakurava looks and feels.",
  "settings.appearance.theme": "Theme",
  "settings.appearance.themeHelper": "Choose your preferred application theme.",
  "settings.appearance.light": "Light",
  "settings.appearance.dark": "Dark",
  "settings.appearance.accentStyle": "Accent Style",
  "settings.appearance.accentStyleHelper": "Select the accent color used across the app.",
  "settings.appearance.sakuraPinkSelected": "Sakura Pink selected",
  "settings.appearance.uiDensity": "UI Density",
  "settings.appearance.uiDensityHelper": "Control the size of UI elements and spacing.",
  "settings.appearance.compact": "Compact",
  "settings.appearance.comfortable": "Comfortable",
  "settings.appearance.spacious": "Spacious",
  "settings.safeFilter.title": "Safe Filter",
  "settings.safeFilter.description": "Control whether R+ catalog content is hidden from normal views.",
  "settings.safeFilter.enabled": "Safe Filter enabled",
  "settings.safeFilter.enabledHelper": "When enabled, directly marked R+ records and sensitive Censorship, Measurements, and Cup Size surfaces are unavailable in normal views.",
  "settings.safeFilter.disableTitle": "Turn off Safe Filter?",
  "settings.safeFilter.disableBody": "R+ catalog content will become visible until you turn Safe Filter on again.",
  "safeFilter.unavailable": "Content is unavailable while Safe Filter is active.",
  "safeFilter.form.directRPlus": "Mark this record as R+",
  "safeFilter.form.glossaryRefs": "Glossary references",
  "safeFilter.form.noGlossary": "No visible Glossary entries are available.",
  "settings.language.title": "Language",
  "settings.language.description":
    "Choose app language and manage custom language packs via CSV.",
  "settings.language.appLanguage": "App Language",
  "settings.language.appLanguageHelper":
    "Choose the language used in the application.",
  "settings.language.catalogDataHelper":
    "Changes apply to app UI only. Catalog data is not translated.",
  "settings.language.csvGuidance.editable":
    "Edit id_lang, language, and translation.",
  "settings.language.csvGuidance.protected":
    "Keep key and context unchanged.",
  "settings.language.csvGuidance.status":
    "One CSV file represents one language. Status is calculated automatically.",
  "settings.language.csvGuidance.englishTemplate":
    "From an English export, change id_lang and language, then translate the translation column.",
  "settings.language.installedLanguages": "Installed Languages",
  "settings.language.installedLanguagesHelper": "Manage installed language packs.",
  "settings.language.upToDate": "Up to date",
  "settings.optimization.title": "Optimization",
  "settings.optimization.description":
    "Manage media access, cache status, and future library optimization.",
  "settings.optimization.mediaLibrary": "Media & Library",
  "settings.optimization.mediaLibraryHelper": "Manage how media files are loaded and processed.",
  "settings.optimization.addMediaRoot": "Add Media Root",
  "settings.optimization.addingMediaRoot": "Adding Media Root...",
  "settings.optimization.cache": "Cache",
  "settings.optimization.cacheHelper": "Manage temporary files used to speed up the app.",
  "settings.optimization.clearCache": "Clear Cache",
  "settings.optimization.clearingCache": "Clearing Cache...",
  "settings.optimization.catalogPreferences": "Catalog Preferences",
  "settings.optimization.catalogPreferencesHelper": "Control how your catalog data is displayed.",
  "settings.dataSafety.title": "Data Safety & Migration",
  "settings.dataSafety.description": "Back up, restore, import, and export data safely.",
  "settings.dataSafety.backupDatabase": "Backup Database",
  "settings.dataSafety.backingUp": "Backing Up...",
  "settings.dataSafety.restoreDatabase": "Restore Database",
  "settings.dataSafety.restoring": "Restoring...",
  "settings.dataSafety.importData": "Import Data",
  "settings.dataSafety.exportData": "Export Data",
  "settings.appInformation.title": "App Information",
  "settings.appInformation.description":
    "Review local runtime status, system safety, and diagnostics.",

  // Home
  "home.welcome": "Welcome to Sakurava",
  "home.welcomeDescription":
    "Manage your local video, image, and performer catalog in one private desktop app.",
  "home.getStarted": "Get Started",
  "home.quickActions": "Quick Actions",
  "home.continueCataloging": "Continue Cataloging",
  "home.recentlyAdded": "Recently Added",
  "home.loadingCatalog": "Loading catalog items...",
  "home.noRecordsYet": "No records yet.",
  "home.noRecentRecords":
    "No recent records yet. Videos, Images, and Performers will appear here after they are saved.",
  "home.summaryVideos": "Videos",
  "home.summaryImages": "Images",
  "home.summaryPerformers": "Performers",
  "home.summaryFavorites": "Favorites",
  "home.addVideo": "Add Video",
  "home.addVideoDetail": "Create a new video catalog item",
  "home.addImage": "Add Image",
  "home.addImageDetail": "Create a new image catalog item",
  "home.addPerformer": "Add Performer",
  "home.addPerformerDetail": "Create a new performer profile",

  // Collection chrome
  "collection.searchPlaceholder.videos": "Search videos...",
  "collection.searchPlaceholder.images": "Search images...",
  "collection.searchPlaceholder.performers": "Search performers...",
  "collection.title.videos": "Videos",
  "collection.title.images": "Images",
  "collection.title.performers": "Performers",
  "collection.subtitle.videos": "Manage your local video catalog",
  "collection.subtitle.images": "Manage your local image catalog",
  "collection.subtitle.performers": "Manage your local performer catalog",
  "collection.addVideo": "Add Video",
  "collection.addImage": "Add Image",
  "collection.addPerformer": "Add Performer",
  "collection.filter": "Filter",
  "collection.view": "View",
  "collection.switchToListView": "Switch to list view",
  "collection.switchToGridView": "Switch to grid view",
  "collection.sorting": "Sorting",
  "collection.categories": "Categories",
  "collection.clearAllFilters": "Clear all filters",
  "collection.clearAll": "Clear all",
  "collection.categoryLimitReached": "Up to 5 category filters can be active.",
  "collection.addCategoryFilter": "Add category filter",
  "collection.pageSize": "Page size",
  "collection.perPage": "per page",
  "collection.previous": "Previous",
  "collection.next": "Next",
  "collection.noMatchingItems": "No matching items",
  "collection.noMatchingItemsHint": "Try a different search term or sort option.",
  "collection.noSavedRecords": "No saved records",
  "collection.noSavedRecordsHint":
    "Collection cards will appear here when saved items are available.",
  "collection.itemsPerPage": "Items per page",
  "collection.availability": "Availability",
  "collection.censorship": "Censorship",
  "collection.releaseYears": "Release Years",
  "collection.allReleaseYears": "All release years",
  "collection.publisherLabel": "Publisher / Label",
  "collection.allPublishers": "All publishers",
  "collection.quality": "Quality",
  "collection.allQuality": "All quality",
  "collection.duration": "Duration",
  "collection.imageCount": "Image Count",
  "collection.status": "Status",
  "collection.cupSize": "Cup Size",
  "collection.allCupSizes": "All cup sizes",
  "collection.gender": "Gender",
  "collection.allGenders": "All genders",
  "collection.noGender": "No Gender values found",
  "collection.bodyHeight": "Body Height",
  "collection.age": "Age",
  "collection.bodyType": "Body Type",
  "collection.allBodyTypes": "All body types",
  "collection.noBodyTypes": "No Body Type categories found",
  "collection.nationality": "Nationality",
  "collection.allNationalities": "All nationalities",
  "collection.debutYears": "Debut Years",
  "collection.allDebutYears": "All debut years",
  "collection.filmographyCount": "Filmography Count",
  "collection.pictorialsCount": "Pictorials Count",
  "collection.category": "Category",
  "collection.openCategoryOptions": "Open Category options",
  "collection.categoryOptions": "Category options",
  "collection.noMatchingCategories": "No matching categories",
  "collection.pagination": "Collection pagination",
  "collection.sortOptions": "Sort options",

  // Shared actions and Categories catalog
  "common.previous": "Previous",
  "common.next": "Next",
  "common.filter": "Filter",
  "common.sort": "Sort",
  "common.perPage": "per page",
  "common.cancel": "Cancel",
  "common.done": "Done",
  "common.remove": "Remove",
  "common.status": "Status",
  "common.action": "Action",
  "common.notAvailable": "Not available",
  "common.notSet": "Not set",
  "app.windowControlsPlaceholder": "Window controls placeholder",
  "common.save": "Save",
  "common.delete": "Delete",
  "common.edit": "Edit",
  "common.add": "Add",
  "common.search": "Search",
  "common.view": "View",
  "common.favorite": "Favorite",
  "common.rating": "Rating",
  "common.categories": "Categories",
  "common.notes": "Notes",
  "common.sourceLinks": "Source Links",
  "common.import": "Import",
  "common.export": "Export",
  "common.back": "Back",
  "common.reset": "Reset",
  "common.clear": "Clear",
  "common.apply": "Apply",
  "common.pageSize": "Page size",
  "common.loading": "Loading",
  "status.loadingVideo": "Loading video...",
  "status.loadingImage": "Loading image...",
  "status.loadingPerformer": "Loading performer...",
  "common.empty": "Empty",
  "common.none": "None",
  "common.records": "Records",
  "common.videos": "Videos",
  "common.images": "Images",
  "common.performers": "Performers",
  "common.credits": "Credits",
  "common.order": "Order",
  "common.roleName": "Role Name",
  "common.creditType": "Credit Type",
  "common.open": "Open",
  "common.browse": "Browse",
  "common.detect": "Detect",
  "common.clearAll": "Clear all",
  "enum.availability.owned": "Owned",
  "enum.availability.notOwned": "Not Owned",
  "enum.availability.missing": "Missing",
  "enum.common.unknown": "Unknown",
  "enum.censorship.uncensored": "Uncensored",
  "enum.censorship.censored": "Censored",
  "enum.censorship.reduced": "Reduced",
  "enum.censorship.leaked": "Leaked",
  "enum.status.active": "Active",
  "enum.status.retired": "Retired",
  "enum.range.short": "Short",
  "enum.range.medium": "Medium",
  "enum.range.long": "Long",
  "enum.height.tall": "Tall",
  "enum.count.few": "Few",
  "enum.count.some": "Some",
  "enum.count.many": "Many",
  "enum.count.all": "All",
  "enum.age.young": "Young",
  "enum.age.adult": "Adult",
  "enum.age.mature": "Mature",
  "enum.age.senior": "Senior",
  "sort.titleAz": "Title A-Z",
  "sort.titleZa": "Title Z-A",
  "sort.nameAz": "Name A-Z",
  "sort.nameZa": "Name Z-A",
  "sort.termAz": "Term A-Z",
  "sort.termZa": "Term Z-A",
  "sort.lastAdded": "Last Added",
  "sort.lastUpdated": "Last Updated",
  "sort.lastModified": "Last Modified",
  "sort.newRelease": "New Release",
  "sort.oldRelease": "Old Release",
  "filter.parentsOnly": "Parents Only",
  "filter.childrenOnly": "Children Only",
  "filter.videosUsed": "Videos Used",
  "filter.imagesUsed": "Images Used",
  "filter.performersUsed": "Performers Used",
  "pagination.showing": "Showing {start}-{end} of {total}",
  "count.videos": "{count} videos",
  "count.video": "{count} video",
  "count.images": "{count} images",
  "count.image": "{count} image",
  "count.performers": "{count} performers",
  "count.performer": "{count} performer",
  "count.selected": "{count} selected",
  "count.selectedVideos": "{count} videos selected",
  "count.selectedImages": "{count} images selected",
  "home.savedVideos": "{count} saved videos",
  "home.savedVideo": "{count} saved video",
  "home.savedImages": "{count} saved images",
  "home.savedImage": "{count} saved image",
  "home.savedPerformers": "{count} saved performers",
  "home.savedPerformer": "{count} saved performer",
  "home.favoriteItems": "{count} favorite items",
  "unit.minute": "minute",
  "unit.minutes": "minutes",
  "unit.image": "image",
  "unit.images": "images",
  "years.activeNow": "{start} - Now",
  "years.duration": "({start} - {end} y)",
  "picker.openVideos": "Open Videos",
  "picker.openImages": "Open Images",
  "picker.openPerformers": "Open Performers",
  "picker.additionalRole": "Additional role",
  "field.title": "Title",
  "field.originalTitle": "Original Title",
  "field.code": "Code",
  "field.name": "Name",
  "field.originalName": "Original Name",
  "field.alias": "Alias",
  "field.availability": "Availability",
  "field.censorship": "Censorship",
  "field.releaseDate": "Release Date",
  "field.publisherLabel": "Publisher / Label",
  "field.duration": "Duration",
  "field.resolution": "Resolution",
  "field.fileSize": "File Size",
  "field.fileType": "File Type",
  "field.imageCount": "Image Count",
  "field.mainResolution": "Main Resolution",
  "field.totalFileSize": "Total File Size",
  "field.mainFileType": "Main File Type",
  "table.name": "Name",
  "table.status": "Status",
  "table.originalName": "Original Name",
  "table.debut": "Debut",
  "table.filmography": "Filmography",
  "table.pictorials": "Pictorials",
  "table.parent": "Parent",
  "table.description": "Description",
  "table.usage": "Usage",
  "table.totalUsage": "Total Usage",
  "field.gender": "Gender",
  "field.birthDate": "Birth Date",
  "field.birthplace": "Birthplace",
  "field.nationality": "Nationality",
  "field.zodiac": "Astrological Sign / Zodiac",
  "field.debutDate": "Debut Date",
  "field.retiredDate": "Retired Date",
  "field.bodyType": "Body Type",
  "field.height": "Height",
  "field.weight": "Weight",
  "field.measurement": "Measurement",
  "field.cupSize": "Cup Size",
  "field.bloodType": "Blood Type",
  "rating.rewatch": "Rewatch",
  "rating.performance": "Performance",
  "rating.visual": "Visual",
  "rating.intensity": "Intensity",
  "rating.story": "Story",
  "rating.chemistry": "Chemistry",
  "rating.memorability": "Memorability",
  "rating.posing": "Posing",
  "rating.atmosphere": "Atmosphere",
  "rating.flow": "Flow",
  "rating.signature": "Signature",
  "rating.attraction": "Attraction",
  "rating.popularity": "Popularity",
  "rating.exceptional": "Exceptional",
  "rating.versatility": "Versatility",
  "app.sidebar.logo": "Sakurava logo",
  "app.sidebar.primaryNavigation": "Primary navigation",
  "app.sidebar.supportNavigation": "Support navigation",
  "shared.pictures": "Pictures",
  "shared.minutes": "Minutes",
  "shared.censorship.censored": "Censored",
  "shared.censorship.uncensored": "Uncensored",
  "shared.censorship.reduced": "Reduced",
  "shared.censorship.leaked": "Leaked",
  "shared.censorship.unknown": "Unknown censorship",
  "categories.title": "Categories",
  "categories.description":
    "Browse category usage across Videos, Images, and Performers.",
  "categories.manage": "Category",
  "categories.summary.total": "Total Category",
  "categories.summary.videos": "Videos Category",
  "categories.summary.images": "Images Category",
  "categories.summary.performers": "Performers Category",
  "categories.search": "Search categories...",
  "categories.searchLabel": "Categories search",
  "categories.filter.all": "All",
  "categories.filter.videoOnly": "Video Only",
  "categories.filter.imageOnly": "Image Only",
  "categories.filter.performerOnly": "Performer Only",
  "categories.sort.name": "Name A-Z",
  "categories.sort.usageHigh": "Usage high-low",
  "categories.sort.usageLow": "Usage low-high",
  "categories.sort.updated": "Last Updated",
  "categories.sort.added": "Last Added",
  "categories.loadError":
    "Category usage could not be loaded. No records were changed.",
  "categories.loading": "Loading category usage...",
  "categories.noMatch": "No categories match the current search and filter.",
  "categories.empty": "No categories yet. Add a category to start managing the catalog vocabulary.",
  "categories.emptyHelper":
    "Record Categories come from saved catalog labels. Managed Categories can be reviewed in Category.",
  "categories.pagination": "Categories pagination",
  "categories.showing":
    "Showing {first}-{last} of {total} categories",
  "categories.page": "Page {page} of {count}",
  "categories.perPageLabel": "Categories per page",
  "category.thumbnailPlaceholder": "Category thumbnail placeholder",
  "category.thumbnailPathSaved": "Thumbnail path saved",
  "detail.edit": "Edit",
  "detail.metadata": "Metadata",
  "detail.categories": "Categories",
  "detail.categoriesLabel": "Detail categories",
  "detail.personal": "Personal",
  "detail.physical": "Physical",
  "detail.bodyType": "Body Type",
  "detail.notAvailable": "N/A",
  "detail.aliases": "Aliases",
  "detail.addFavorite": "Add to Favorites",
  "detail.removeFavorite": "Remove from Favorites",
  "detail.systemInfo": "System Info",
  "detail.notRated": "Not rated",
  "detail.ratingUnavailable": "Rating not available for a readable spider chart.",
  "detail.ratingRadar": "Rating radar map",
  "detail.notes": "Notes",
  "detail.sourceLinks": "Source Links",
  "detail.sourceLink": "Source Link",
  "detail.role": "Role",
  "detail.creditType": "Credit Type",
  "detail.relatedPerformers": "Related Performers",
  "detail.performerHeroChips": "Performer hero chips",
  "detail.relatedPerformer": "Related performer",
  "detail.relatedSortOptions": "Related sort options",
  "detail.relatedPagination": "Related section pagination",
  "detail.table.availabilityShort": "AVAIL",
  "detail.table.favoriteShort": "FAV",
  "detail.table.titleShort": "TITLE",
  "detail.table.codeShort": "CODE",
  "detail.table.censorshipShort": "CENSOR",
  "detail.table.ratingShort": "RATING",
  "detail.collapseCategories": "Collapse categories",
  "detail.previousRelated": "Previous related items",
  "detail.nextRelated": "Next related items",
  "detail.relatedVideos": "Related Videos",
  "detail.relatedImages": "Related Images",
  "detail.unavailable": "Unavailable",
  "detail.search": "Search",
  "detail.searchRelated": "Search related items",
  "detail.view": "View",
  "detail.titleColumn": "Title",
  "detail.releaseDateColumn": "Release Date",
  "detail.gallery": "Gallery",
  "detail.galleryShowing": "Showing {shown} of {total} images",
  "detail.galleryEmpty": "No Gallery Images saved.",
  "detail.backVideos": "Back to Videos",
  "detail.backImages": "Back to Images",
  "detail.backPerformers": "Back to Performers",
  "detail.ratingSummary": "Rating Summary",
  "detail.created": "Created in Sakurava",
  "detail.lastEdited": "Last edited",
  "detail.yearsActive": "Years Active",
  "detail.noNote": "No note saved",
  "detail.noNotes": "No notes saved.",
  "detail.videoTitle": "Video Detail",
  "detail.imageTitle": "Image Detail",
  "detail.performerTitle": "Performer Detail",
  "detail.videoSubtitle": "View saved video catalog information",
  "detail.imageSubtitle": "View a local image catalog item",
  "detail.performerSubtitle": "View profile, catalog summary, and personal notes",
  "detail.videoMissing": "This video could not be found.",
  "detail.imageMissing": "This image could not be found.",
  "detail.performerMissing": "This performer could not be found.",
  "detail.loadMore": "Load More",
  "detail.showAll": "Show All",
  "detail.play": "Play",
  "form.basicIdentity": "Basic Identity",
  "form.aliases": "Aliases",
  "form.addAlias": "Add alias...",
  "form.favorite": "Favorite",
  "form.metadata": "Metadata",
  "form.files": "File",
  "form.filmography": "Filmography",
  "form.pictorials": "Pictorials",
  "form.profileDetails": "Profile Details",
  "form.categories": "Categories",
  "form.rating": "Rating",
  "form.averageAuto": "Average: Auto",
  "form.relatedPerformers": "Related Performers",
  "form.relatedVideos": "Related Videos",
  "form.relatedImages": "Related Images",
  "form.notes": "Notes",
  "form.notesPlaceholder": "Write local notes...",
  "form.measurements": "Measurements",
  "form.measurementsUnit": "Measurements unit",
  "form.galleryPath": "Gallery Path",
  "form.miniThumbnailPaths": "Mini Thumbnail Paths",
  "form.availability": "Availability",
  "form.sourceLinks": "Source Links",
  "form.sourceUrlPlaceholder": "https://example.com/source",
  "form.remove": "Remove",
  "form.fromRoleName": "From role name",
  "form.searchCategories": "Search categories",
  "form.clearCategorySearch": "Clear category search",
  "form.noSourceLinks": "No source links added.",
  "form.addSourceLink": "Add Source Link",
  "form.techInfo": "Tech Info",
  "form.file": "File",
  "form.videoCreateLabel": "Video Create Form",
  "form.videoEditLabel": "Video Edit Form",
  "form.imageCreateLabel": "Image Create Form",
  "form.imageEditLabel": "Image Edit Form",
  "form.performerCreateLabel": "Performer Create Form",
  "form.performerEditLabel": "Performer Edit Form",
  "form.addVideo": "Add Video",
  "form.editVideo": "Edit Video",
  "form.addImage": "Add Image",
  "form.editImage": "Edit Image",
  "form.addPerformer": "Add Performer",
  "form.editPerformer": "Edit Performer",
  "form.createVideoSubtitle": "Create a new video catalog item",
  "form.updateVideoSubtitle": "Update a local video catalog item",
  "form.createImageSubtitle": "Create a new image catalog item",
  "form.updateImageSubtitle": "Update a local image catalog item",
  "form.createPerformerSubtitle": "Create a new performer profile",
  "form.updatePerformerSubtitle": "Update a local performer profile",
  "form.backVideoDetail": "Back to Video Detail",
  "form.backImageDetail": "Back to Image Detail",
  "form.backPerformerDetail": "Back to Performer Detail",
  "form.categorySearchVideo": "Search categories, genre, setting, attribute...",
  "form.categorySearchImage": "Search categories, face, body, pose, setting...",
  "form.categorySearchPerformer": "Search categories, face, body, specialty, attribute...",
  "form.noCategories": "No categories selected.",
  "form.manageCategory": "Category",
  "form.galleryEmpty": "No Gallery Path rows added.",
  "form.addFolder": "Add Folder",
  "form.addImages": "Add Images",
  "form.clearAll": "Clear All",
  "form.miniThumbnailEmpty": "No Mini Thumbnail Path row added.",
  "form.thumbnailSelected": "{count}/4 selected",
  "form.astrologicalSign": "Astrological Sign",
  "form.notSet": "Not set",
  "picker.relatedImages.searchPlaceholder": "Search image title, album, tag...",
  "picker.relatedImages.empty": "No related images selected.",
  "picker.relatedVideos.searchPlaceholder": "Search video title, code, performer...",
  "picker.relatedVideos.empty": "No related videos selected.",
  "common.status.available": "Available",
  "common.count.minute": "{count} minute",
  "common.count.minutes": "{count} minutes",
  "common.count.min": "{count} min",
  "common.count.image": "{count} image",
  "common.count.images": "{count} images",
  "common.count.pic": "{count} pic",
  "common.count.pics": "{count} pics",
  "common.count.video": "{count} video",
  "common.count.videos": "{count} videos",
  "common.count.set": "{count} set",
  "common.count.sets": "{count} sets",
  "common.count.performer": "{count} performer",
  "common.count.performers": "{count} performers",
  "common.count.more": "+{count} more",
  "common.filter.rating.any": "Any",
  "catalog.empty": "Empty Catalog",
  "catalog.filterChip.category": "Category",
  "catalog.filterChip.availability": "Availability",
  "catalog.filterChip.censorship": "Censorship",
  "catalog.filterChip.releaseYears": "Release Years",
  "catalog.filterChip.publisherLabel": "Publisher / Label",
  "catalog.filterChip.quality": "Quality",
  "catalog.filterChip.rating": "Rating",
  "catalog.filterChip.duration": "Duration",
  "catalog.filterChip.imageCount": "Image Count",
  "catalog.filterChip.cupSize": "Cup Size",
  "catalog.filterChip.gender": "Gender",
  "catalog.filterChip.bodyHeight": "Body Height",
  "catalog.filterChip.age": "Age",
  "catalog.filterChip.bodyType": "Body Type",
  "catalog.filterChip.nationality": "Nationality",
  "catalog.filterChip.debutYears": "Debut Years",
  "catalog.filterChip.filmographyCount": "Filmography Count",
  "catalog.filterChip.pictorialsCount": "Pictorials Count",
  "catalog.filterValue.ratingStars": "{count} star",
  "catalog.filterValue.older": "Older",
  "catalog.table.header.availability": "AVAILABILITY",
  "catalog.table.header.title": "TITLE",
  "catalog.table.header.originalTitle": "ORIGINAL TITLE",
  "catalog.table.header.code": "CODE",
  "catalog.table.header.categories": "CATEGORIES",
  "catalog.table.header.release": "RELEASE",
  "catalog.table.header.duration": "DURATION",
  "catalog.table.header.totalPics": "TOTAL PICS",
  "catalog.table.header.quality": "QUALITY",
  "catalog.table.header.censorship": "CENSORSHIP",
  "catalog.table.header.rating": "RATING",
  "catalog.table.header.name": "NAME",
  "catalog.table.header.originalName": "ORIGINAL NAME",
  "catalog.table.header.debut": "DEBUT",
  "catalog.table.header.filmography": "FILMOGRAPHY",
  "catalog.table.header.pictorials": "PICTORIALS",
  "form.file.coverPath": "Cover Path",
  "form.file.mediaPath": "Media Path",
  "form.placeholder.videoTitle": "Video title",
  "form.placeholder.originalVideoTitle": "Original release title",
  "form.placeholder.videoCode": "VID-001",
  "form.placeholder.imageTitle": "Image set title",
  "form.placeholder.originalImageTitle": "Original image set release title",
  "form.placeholder.imageCode": "IMG-001",
  "form.placeholder.performerName": "Performer name",
  "form.placeholder.originalPerformerName": "Original performer name",
  "form.placeholder.publisherLabel": "Studio or label",
  "common.value.notAvailable": "n/a",
  "form.gallery.moreFiles": "+{count} more files are loaded",
  "form.gallery.showAll": "Show All",
  "form.gallery.showLess": "Show Less",
  "form.category.selectedOne": "{count} category selected.",
  "form.category.selectedMany": "{count} categories selected.",
  "form.category.noMatches": "No matching Managed Categories. Use Category to add it first.",
  "form.confirm.saveChanges.title": "Save changes?",
  "form.confirm.saveChanges.description": "The saved record will be updated with these changes.",
  "form.confirm.saveChanges.action": "Save changes",
  "form.confirm.discard.title": "Discard changes?",
  "form.confirm.discard.description": "Unsaved changes will be lost.",
  "form.confirm.discard.action": "Discard",
  "form.confirm.delete.title": "Delete {title}?",
  "form.confirm.delete.description": "This removes the saved Sakurava record for {title}. It does not delete local media files from this device.",
  "categories.table.header.name": "NAME",
  "categories.table.header.description": "DESCRIPTION",
  "categories.table.header.parent": "PARENT",
  "categories.table.header.usage": "USAGE",
  "categories.table.header.totalUsage": "TOTAL USAGE",
  "detail.performer.relatedVideos.table.header.total": "TOTAL",
  "detail.performer.relatedImages.table.header.total": "TOTAL",
  "detail.related.table.header.title": "TITLE",
  "detail.related.table.header.releaseDate": "RELEASE DATE",
  "detail.related.table.header.duration": "DURATION",
  "detail.related.table.header.total": "TOTAL",
  "detail.related.empty.performers": "No related performers saved.",
  "detail.related.empty.images": "No related images saved.",
  "detail.related.empty.videos": "No related videos saved.",
  "detail.system.coverStatus": "Cover status",
  "detail.system.mediaStatus": "Media status",
  "detail.system.galleryStatus": "Gallery status",
  "detail.system.profileImageStatus": "Profile image status",
  "detail.performer.yearsActive.duration": "({start} - {end} y)",
  "glossary.form.field.category": "Category",
  "glossary.form.field.thumbnail": "Thumbnail",
  "glossary.table.header.term": "TERM",
  "glossary.table.header.synonyms": "SYNONYMS",
  "glossary.table.header.categories": "CATEGORIES",
  "glossary.table.header.definition": "DEFINITION",
  "glossary.table.header.source": "SOURCE",
  "categories.toolbar.filter": "Filter",
  "categories.toolbar.clearAllFilters": "Clear all filters",
  "categories.noMatches": "No categories match the current search, filter, and sort view.",
  "categories.noMatchingFilters": "No matching filters",
  "glossary.toolbar.clearAllFilters": "Clear all filters",
  "glossary.empty": "No glossary entries found",
  "glossary.emptyHint": "Try a different search term or category filter, or add a new Glossary entry.",
  "settings.import.preview.table.header.row": "ROW",
  "settings.import.preview.table.header.action": "ACTION",
  "settings.import.preview.table.header.result": "RESULT",
  "settings.import.preview.table.header.target": "TARGET",
  "settings.import.preview.table.header.changes": "CHANGES",
  "settings.import.preview.table.header.status": "STATUS",
  "settings.import.report.table.header.message": "MESSAGE",
  "viewer.fullSize": "Gallery full-size viewer",
  "viewer.metadata": "Image metadata",
  "viewer.actions": "Image viewer actions",
  "viewer.showShortcuts": "Show image viewer shortcuts",
  "viewer.aspectRatio": "Image aspect ratio",
  "viewer.openFolder": "Open image folder",
  "viewer.more.openFolder": "Open Folder",
  "viewer.moreActions": "More image actions",
  "viewer.shortcuts": "Image viewer shortcuts",
  "viewer.shortcutsTitle": "Shortcuts",
  "viewer.shortcuts.action.closeViewer": "Close viewer",
  "viewer.shortcuts.navigate": "Navigate images",
  "viewer.shortcuts.zoom": "Zoom in or out",
  "viewer.shortcuts.fitWindow": "Fit to window",
  "viewer.shortcuts.actualSize": "Show at 100%",
  "viewer.shortcuts.fullWindow": "Toggle full-window mode",
  "viewer.shortcuts.zoomPointer": "Zoom around pointer",
  "viewer.shortcuts.panZoomed": "Pan when zoomed",
  "viewer.shortcuts.key.esc": "Esc",
  "viewer.shortcuts.key.leftRight": "Left / Right",
  "viewer.shortcuts.key.zoom": "+ / -",
  "viewer.shortcuts.key.fit": "0 / F",
  "viewer.shortcuts.key.actualSize": "1",
  "viewer.shortcuts.key.fullWindow": "F11",
  "viewer.shortcuts.key.wheel": "Wheel",
  "viewer.shortcuts.key.drag": "Drag",
  "viewer.moreActionsMenu": "More image actions menu",
  "viewer.saved": "Saved",
  "viewer.more.saveAs": "Save As",
  "viewer.saving": "Saving...",
  "viewer.opening": "Opening...",
  "viewer.more.copyPath": "Copy Image Path",
  "viewer.copied": "Copied",
  "viewer.more.copyName": "Copy File Name",
  "viewer.more.alwaysShowControls": "Always Show Controls",
  "viewer.more.rememberSettings": "Remember Viewer Settings",
  "viewer.fileInfoLabel": "Image file info",
  "viewer.more.fileInfo": "File Info",
  "viewer.fileInfo.name": "Name",
  "viewer.fileInfo.fileType": "File Type",
  "viewer.fileInfo.dimension": "Dimension",
  "viewer.fileInfo.size": "Size",
  "viewer.fileInfo.dateTaken": "Date Taken",
  "viewer.fileInfo.path": "Path",
  "viewer.previous": "Previous gallery image",
  "viewer.next": "Next gallery image",
  "viewer.panSurface": "Image pan surface",
  "viewer.unavailable": "Image unavailable",
  "viewer.bottomDock": "Image viewer bottom dock",
  "viewer.positionOverview": "Image position overview",
  "viewer.minimap": "Image minimap navigator",
  "viewer.controls": "Image viewer controls",
  "viewer.openZoom": "Open gallery image zoom controls",
  "viewer.zoomControl": "Gallery image zoom control",
  "viewer.zoomOut": "Zoom out gallery image",
  "viewer.zoomValue": "Image zoom value",
  "viewer.setZoom": "Set gallery image zoom percentage",
  "viewer.zoomIn": "Zoom in gallery image",
  "viewer.zoomControls": "Gallery image zoom controls",
  "viewer.openRotation": "Open gallery image rotation controls",
  "viewer.rotationControl": "Gallery image rotation control",
  "viewer.rotateLeft": "Rotate gallery image left",
  "viewer.rotationValue": "Image rotation value",
  "viewer.setRotation": "Set image rotation degrees",
  "viewer.rotateRight": "Rotate gallery image right",
  "viewer.rotationControls": "Gallery image rotation controls",
  "viewer.reset": "Reset gallery image view",
  "viewer.moreControls": "More viewer controls",
  "viewer.moreControlsMenu": "More viewer controls menu",
  "settings.search": "Search settings",
  "settings.overview": "Overview",
  "settings.overview.theme": "Theme",
  "settings.overview.language": "Language",
  "settings.overview.mediaLibrary": "Media Library",
  "settings.overview.database": "Database",
  "settings.overview.lastBackup": "Last Backup",
  "settings.overview.cache": "Cache",
  "settings.overview.storage": "Storage",
  "settings.overview.notConfigured": "Not configured",
  "settings.overview.localOffline": "Local / Offline",
  "settings.appearance.system": "System",
  "settings.appearance.accentColor": "Accent Color",
  "settings.appearance.customAccent": "Custom accent color",
  "settings.appearance.customAccentPicker": "Custom accent color picker",
  "settings.appearance.density": "Density",
  "settings.appearance.uiScale": "UI Scale",
  "settings.language.manage": "Manage...",
  "settings.language.closeManage": "Close Manage",
  "settings.language.management": "Installed language management",
  "settings.language.defaultProtected": "Default · Source · Protected",
  "settings.language.installedCustom": "Installed · Custom · {code}",
  "settings.language.protected": "Protected",
  "settings.language.remove": "Remove",
  "settings.language.removeLanguage": "Remove Language",
  "settings.language.removeLabel": "Remove custom language {name}",
  "settings.language.custom": "Custom Language",
  "settings.language.importCsv": "Import Language CSV",
  "settings.language.exportCsv": "Export Language CSV",
  "settings.language.csvPreview.title": "Translation CSV Preview",
  "settings.language.csvPreview.detectedFormat": "Detected format",
  "settings.language.csvPreview.targetLanguage": "Target language",
  "settings.language.csvPreview.targetLabel": "Language name",
  "settings.language.csvPreview.targetCode": "Language code",
  "settings.language.csvPreview.sourceRows": "Source rows",
  "settings.language.csvPreview.ignoredBlankRows": "Ignored blank rows",
  "settings.language.csvPreview.createCount": "Translated / Create",
  "settings.language.csvPreview.updateCount": "Updated",
  "settings.language.csvPreview.resetCount": "Reset / Use English",
  "settings.language.csvPreview.unchangedCount": "Unchanged",
  "settings.language.csvPreview.warningCount": "Warnings",
  "settings.language.csvPreview.errorCount": "Errors",
  "settings.language.csvPreview.blocked": "Apply is blocked until every error and required decision is resolved.",
  "settings.language.csvPreview.previewAgain": "Preview Again",
  "settings.language.csvPreview.historicalBuiltIn": "Historical built-in text",
  "settings.language.csvPreview.identicalEnglish": "Text identical to English",
  "settings.language.csvPreview.treatAsMissing": "Treat as missing",
  "settings.language.csvPreview.preserveOverride": "Preserve as custom override",
  "settings.language.csv.importPending": "Reading Translation CSV...",
  "settings.language.csv.exportPending": "Exporting Translation CSV...",
  "settings.language.csv.cancelled": "Translation CSV export was cancelled.",
  "settings.language.csv.exportSuccess": "Language CSV exported to {path}",
  "settings.language.csv.exportFailure": "Translation CSV could not be exported.",
  "settings.language.csvPreview.formatValue": "Format {format}",
  "settings.language.csvPreview.sakuravaFormat": "Sakurava Translation CSV",
  "settings.language.csvPreview.labelChange": "Language name change",
  "settings.language.resetPreview.formatValue": "English reset",
  "settings.language.csvApply.confirmTitle": "Apply Translation CSV?",
  "settings.language.csvApply.confirmAction": "Apply Translation CSV",
  "settings.language.csvApply.pending": "Applying Translation CSV...",
  "settings.language.csvApply.safety": "All changes use one recoverable logical transaction. Catalog and user data are not modified.",
  "settings.language.csvApply.success": "Translation CSV applied and verified.",
  "settings.language.csvApply.successCounts": "Translation CSV applied and verified. {creates} created, {updates} updated, {resets} reset.",
  "settings.language.csvApply.unchangedCounts": "Translation CSV applied and verified. {unchanged} unchanged.",
  "settings.language.csvApply.failure": "Translation CSV was not applied.",
  "settings.language.csvApply.stale": "This Preview is stale because Translation storage changed. Create a new Preview.",
  "settings.language.csvApply.rollback": "The failed change was rolled back and verified.",
  "settings.language.csvApply.recoveryRequired": "The Translation transaction requires explicit recovery.",
  "settings.language.resetEnglish": "Reset English",
  "settings.language.resetPreview.title": "English Reset Preview",
  "settings.language.resetPreview.count": "English overrides to remove",
  "settings.language.resetPreview.unchanged": "English already matches the bundled baseline. No change is needed.",
  "settings.language.resetConfirm.title": "Reset English to its bundled baseline?",
  "settings.language.resetConfirm.body": "Custom languages, custom-language overrides, the selected language, catalog records, and user data remain unchanged.",
  "settings.language.resetConfirm.action": "Reset English",
  "settings.language.resetConfirm.pending": "Resetting English...",
  "settings.language.reset.success": "English was reset to the bundled baseline and verified.",
  "settings.language.storage.warningTitle": "Translation storage needs attention",
  "settings.language.storage.clean": "Translation storage is ready.",
  "settings.language.storage.recoverable": "Some Translation data could not be parsed safely.",
  "settings.language.storage.ambiguous": "Translation storage contains ambiguous duplicate data.",
  "settings.language.storage.fatal": "Multiple Translation storage values are malformed.",
  "settings.language.storage.transactionRequired": "A pending Translation transaction requires recovery.",
  "settings.language.storage.preserved": "Exact Translation data and transaction evidence were preserved.",
  "settings.language.storage.noAutomaticRepair": "No automatic repair or journal clearing was performed.",
  "settings.language.storage.recoverableTransaction": "Recovery uses the recorded before or after state from a recoverable logical transaction.",
  "settings.language.recovery.restorePrevious": "Restore Previous Translation State",
  "settings.language.recovery.complete": "Complete Translation Transaction",
  "settings.language.recovery.pending": "Recovering Translation storage...",
  "settings.language.recovery.success": "Translation storage recovery completed and was verified.",
  "settings.language.recovery.failure": "Translation storage recovery could not be verified.",
  "settings.language.recovery.export": "Export Recovery JSON",
  "settings.language.recovery.exportPending": "Exporting Recovery JSON...",
  "settings.language.recovery.exportSuccess": "Translation recovery JSON exported successfully.",
  "settings.language.recovery.exportFailure": "Translation recovery JSON could not be exported.",
  "settings.language.recovery.cancelled": "Translation recovery export was cancelled.",
  "settings.catalogPreferences.title": "Catalog Preferences",
  "settings.catalogPreferences.defaultView": "Default View",
  "settings.catalogPreferences.defaultSort": "Default Sort",
  "settings.catalogPreferences.remember": "Remember Preferences",
  "settings.catalogPreferences.grid": "Grid",
  "settings.catalogPreferences.dateAdded": "Date Added",
  "settings.catalogPreferences.rememberView": "Remember catalog view",
  "settings.catalogPreferences.rememberSort": "Remember catalog sort",
  "settings.catalogPreferences.rememberFilters": "Remember catalog filters",
  "settings.catalogPreferences.helper": "Remembers view, sort, and structured filters only. Search, page size, and pagination are never saved.",
  "settings.library.title": "Library & Media",
  "settings.library.mediaRoot": "Media Root",
  "settings.library.configuredRoots": "Configured media roots",
  "settings.library.noFolders": "No folders configured",
  "settings.library.remove": "Remove...",
  "settings.libraryMedia.addFolder": "Add Folder...",
  "settings.libraryMedia.adding": "Adding...",
  "settings.libraryMedia.addRootAria": "Add Media Root",
  "settings.libraryMedia.removeRootAria": "Remove Media Root",
  "settings.libraryMedia.pending": "Adding media root...",
  "settings.libraryMedia.addSuccess": "Media root enabled for thumbnails: {path}",
  "settings.libraryMedia.duplicateRoot": "{path} is already configured.",
  "settings.libraryMedia.removeSuccess": "Configured media root removed. It will no longer be restored after restart.",
  "settings.libraryMedia.removeHelp": "Removing a configured root does not delete media files. Its current app-session access may remain until restart.",
  "settings.libraryMedia.error.required": "Select a media folder to add.",
  "settings.libraryMedia.error.missing": "The selected media folder no longer exists.",
  "settings.libraryMedia.error.notFolder": "The selected media root must be a folder.",
  "settings.libraryMedia.error.filesystemRoot": "Choose a folder instead of a drive or filesystem root.",
  "settings.libraryMedia.error.generic": "The media root could not be enabled.",
  "settings.managedMedia.regenerate": "Regenerate Missing / Outdated",
  "settings.managedMedia.regenerating": "Preparing mini images...",
  "settings.managedMedia.queued": "{count} mini image sources queued.",
  "settings.managedMedia.upToDate": "Mini images are up to date.",
  "settings.managedMedia.error": "Mini images could not be queued. Try again.",
  "settings.backup.title": "Backup & Recovery",
  "settings.backup.status.title": "Backup Status",
  "settings.backup.lastBackup": "Last Backup",
  "settings.backup.location": "Backup Location",
  "settings.backup.location.title": "Backup Location",
  "settings.backup.location.default": "Sakurava backup folder",
  "settings.backup.location.change": "Change Location",
  "settings.backup.location.description": "Backups are stored in Sakurava app data. No destination selection is required.",
  "settings.backup.openFolder": "Open Backup Folder",
  "settings.backup.openFolderShort": "Open Folder",
  "settings.backup.manual.title": "Manual Backup",
  "settings.backup.note.label": "Optional note",
  "settings.backup.note.placeholder": "Add a note for this backup",
  "settings.backup.note.placeholderFinal": "Add an optional note for this backup...",
  "settings.backup.backupNow": "Backup Now",
  "settings.backup.backingUp": "Backing up...",
  "settings.backup.lastBackupValue": "Last backup: {createdAt}",
  "settings.backup.status.created": "Backup created.",
  "settings.backup.packageCount": "Backup Packages",
  "settings.backup.packageCountValue.one": "{count} package",
  "settings.backup.packageCountValue.other": "{count} packages",
  "settings.backup.type.manual": "Manual",
  "settings.backup.type.automatic": "Automatic",
  "settings.backup.type.auto": "Auto",
  "settings.backup.status.success": "Success",
  "settings.backup.automatic.title": "Automated Backup",
  "settings.backup.automatic.helper": "Create backups on a schedule",
  "settings.backup.automatic.frequency": "Frequency",
  "settings.backup.automatic.daily": "Daily",
  "settings.backup.automatic.weekly": "Weekly",
    "settings.backup.automatic.monthly": "Monthly",
    "settings.backup.automatic.disabled": "Disabled",
    "settings.backup.automatic.enabled": "Waiting for the next scheduled check",
    "settings.backup.automatic.running": "Creating automatic backup...",
    "settings.backup.automatic.success": "Automatic backup created.",
    "settings.backup.automatic.retry":
      "Automatic backup could not run. It will retry at the next check.",
    "settings.backup.automatic.lastSuccess":
      "Last automatic backup: {createdAt}",
  "settings.backup.history.title": "Backup History",
  "settings.backup.history.refresh": "Refresh backup history",
  "settings.backup.history.dateTime": "Date & Time",
  "settings.backup.history.selection": "Selection",
  "settings.backup.history.size": "Size",
  "settings.backup.history.type": "Type",
  "settings.backup.history.status": "Status",
  "settings.backup.history.note": "Note",
  "settings.backup.history.actions": "Actions",
  "settings.backup.history.view": "View backup",
  "settings.backup.history.more": "More backup actions",
  "settings.backup.history.restore": "Restore",
  "settings.backup.history.download": "Download",
  "settings.backup.history.delete": "Delete",
  "settings.backup.management.downloading": "Downloading...",
  "settings.backup.management.downloadSuccess": "Backup downloaded.",
  "settings.backup.management.downloadError":
    "Backup could not be downloaded. Please try again.",
  "settings.backup.management.deleteConfirmTitle": "Delete this backup?",
  "settings.backup.management.deleteConfirmBody":
    "This removes the backup package from Sakurava's backup folder. Your current library will not be changed.",
  "settings.backup.management.deleteConfirmBodyRefined":
    "This backup will be permanently removed. Your current catalog will not be changed.",
  "settings.backup.management.deleteConfirmAction": "Delete Backup",
  "settings.backup.management.deleting": "Deleting...",
  "settings.backup.management.deleteSuccess": "Backup deleted.",
  "settings.backup.management.deleteError":
    "Backup could not be deleted. Please try again.",
  "settings.backup.toast.created": "Backup created",
  "settings.backup.toast.createError": "Backup could not be created",
  "settings.backup.toast.imported": "Backup imported",
  "settings.backup.toast.importError": "Backup could not be imported",
  "settings.backup.toast.downloaded": "Backup downloaded",
  "settings.backup.toast.downloadError": "Backup could not be downloaded",
  "settings.backup.toast.deleted": "Backup deleted",
  "settings.backup.toast.deleteError": "Backup could not be deleted",
  "settings.backup.toast.close": "Close notification",
  "settings.backup.importSelected.action": "Restore from Backup...",
  "settings.backup.importSelected.importing": "Importing backup...",
  "settings.backup.importSelected.error.invalid":
    "This backup could not be used. Please choose a valid Sakurava backup package.",
  "settings.backup.importSelected.error.generic":
    "Backup could not be imported. Please try again.",
  "settings.backup.history.showing": "Showing {start}-{end} of {total}",
  "settings.backup.history.pageSize": "Page size",
  "settings.backup.history.perPage": "per page",
  "settings.backup.validating": "Validating backup...",
  "settings.backup.list.title": "Backup Packages",
  "settings.backup.list.empty": "No backup packages available.",
  "settings.backup.preview.title": "Backup Preview",
  "settings.backup.preview.name": "Backup Name",
  "settings.backup.previewing": "Previewing...",
  "settings.backup.preview.databaseIncluded": "Database included",
  "settings.backup.preview.createdAt": "Created: {createdAt}",
  "settings.backup.preview.type": "Type: {type}",
  "settings.backup.preview.note": "Note: {note}",
  "settings.backup.preview.glossary": "Glossary",
  "settings.backup.preview.credits": "Credits",
  "settings.backup.restoreAction": "Restore Backup",
  "settings.backup.restoring": "Restoring backup package...",
  "settings.backup.restoreConfirm.title": "Restore this backup?",
  "settings.backup.restoreConfirm.bodyRefined": "Current catalog and app data will be replaced. A safety backup will be created first.",
  "settings.backup.restoreConfirm.mediaUnaffectedRefined": "Original media files will not be changed.",
  "settings.backup.restoreConfirm.replaceDatabase": "The current Sakurava database will be replaced by the selected backup package.",
  "settings.backup.restoreConfirm.safetyPackage": "A safety package of the current database will be created before restore.",
  "settings.backup.restoreConfirm.mediaUnaffected": "Original media files are not restored, deleted, or changed.",
  "settings.backup.restoreConfirm.missingMedia": "Restore cannot recover missing external media files.",
  "settings.backup.restoreConfirm.package": "Package: {packageName}",
  "settings.backup.restoreConfirm.confirm": "Confirm Restore",
  "settings.backup.restoreConfirm.cancel": "Cancel",
  "settings.backup.result.title": "Restore Result",
  "settings.backup.summary.title": "Restore Summary",
  "settings.backup.summary.restoredBackup": "Restored backup",
  "settings.backup.summary.restoredOn": "Restored on",
  "settings.backup.summary.backupType": "Backup type",
  "settings.backup.summary.safetyBackup": "Safety backup",
  "settings.backup.summary.finalStatus": "Final status",
  "settings.backup.summary.success": "Your data was restored successfully.",
  "settings.backup.result.restored": "Restored package: {packageName}",
  "settings.backup.safetyPackageCreated": "Safety package created: {packageName}",
  "settings.backup.result.rollback": "Rollback: {status}",
  "settings.backup.result.rollbackSucceeded": "completed",
  "settings.backup.result.rollbackFailed": "failed",
  "settings.backup.result.rollbackNotRequired": "not required",
  "settings.backup.error.generic": "Backup package creation failed.",
  "settings.backup.error.tooSoon": "A backup was just created. Please wait a moment before creating another one.",
  "settings.backup.error.list": "Backup packages could not be loaded.",
  "settings.backup.error.openFolder": "The Sakurava backup folder could not be opened.",
  "settings.backup.error.preview": "Backup package preview failed.",
  "settings.backup.error.restore": "Backup package restore failed.",
  "settings.backup.error.restoreRollback": "Restore failed and the safety rollback did not complete. Keep Sakurava open and review the backup folder.",
  "settings.importExport.title": "Import / Export",
  "settings.importExport.importCatalog": "Import Catalog",
  "settings.importExport.exportCatalog": "Export Catalog",
  "settings.importExport.downloadTemplate": "Download Template",
  "settings.importExport.changeFile": "Change File",
  "settings.importExport.needsReview": "Needs Review",
  "settings.importExport.attention": "Attention",
  "settings.importExport.ready": "Ready",
  "settings.importExport.reading": "Reading catalog file...",
  "settings.importExport.exporting": "Exporting...",
  "settings.importExport.filters": "Import row filters",
  "settings.importExport.filter.all": "All",
  "settings.importExport.filter.add": "Add",
  "settings.importExport.filter.create": "Create",
  "settings.importExport.filter.update": "Update",
  "settings.importExport.filter.delete": "Delete",
  "settings.importExport.filter.skip": "Skip",
  "settings.importExport.filter.error": "Needs Review",
  "settings.importExport.filter.attention": "Attention",
  "settings.importExport.filter.warning": "Warning",
  "settings.importExport.searchRows": "Search rows",
  "settings.importExport.table.row": "Row",
  "settings.importExport.table.section": "Section",
  "settings.importExport.table.ref": "Sakurava Ref",
  "settings.importExport.table.record": "Record",
  "settings.importExport.table.action": "Action",
  "settings.importExport.table.issue": "Issue",
  "settings.importExport.table.details": "Details",
  "settings.importExport.table.status": "Status",
  "settings.importExport.generatedRef": "A new Sakurava Ref will be generated",
  "settings.importExport.selectSections": "Select sections to export",
  "settings.importExport.chooseFormat": "Choose export format",
  "settings.importExport.recommended": "Recommended",
  "settings.importExport.compatibility": "Compatibility",
  "settings.importExport.summary": "Summary",
  "settings.importExport.sectionsSelected": "{count} sections selected",
  "settings.importExport.formatSummary": "Format: {format}",
  "settings.importExport.exportAsTemplate": "Export as template",
  "settings.importExport.templateSummary": "Template: {state}",
  "settings.importExport.templateOn": "On",
  "settings.importExport.templateOff": "Off",
  "settings.importExport.templateLabel": "Template",
  "settings.importExport.recordsSelected": "{count} records",
  "settings.importExport.emptySections": "No records in {sections}. Turn on Export as template to continue.",
  "settings.importExport.exportSelected": "Export Selected",
  "settings.importExport.applyImport": "Apply Import",
  "settings.importExport.noChanges": "No Changes",
  "settings.importExport.skipped": "Skipped",
  "settings.importExport.details.create": "New record will be added",
  "settings.importExport.details.delete": "Record will be deleted",
  "settings.importExport.details.skip": "Row will be skipped",
  "settings.importExport.details.noChanges": "No changes",
  "settings.importExport.details.review": "Review this row",
  "settings.importExport.details.changeValue": "{field} changes from “{before}” to “{after}”",
  "settings.importExport.details.updateField": "{field} will be updated",
  "settings.importExport.details.updateFields": "{count} fields will change",
  "settings.importExport.details.updateFieldsNamed": "{count} fields ({fields}) will change",
  "settings.importExport.details.cleared": "Cleared",
  "settings.importExport.details.valueWillBeCleared": "Value will be cleared",
  "settings.importExport.details.invalidDate": "Date is not valid for this computer",
  "settings.importExport.details.idNotFound": "Record ID was not found",
  "settings.importExport.details.requiredMissing": "Required {field} is missing",
  "settings.importExport.details.invalidFavorite": "Favorite must be true or false",
  "settings.importExport.details.invalidParentId": "Parent Glossary ID is not valid",
  "settings.importExport.details.selfParent": "A Glossary record cannot be its own parent",
  "settings.importExport.details.parentNotFound": "Parent Glossary record was not found",
  "settings.importExport.rows": "rows",
  "settings.importExport.rowsNeedReview": "{count} rows need review.",
  "settings.importExport.itemsRequireDecision": "{count} items require a decision.",
  "settings.importExport.reviewItems": "Review {count} items",
  "settings.importExport.reviewResolutionHelp": "Choose how Sakurava should preserve the remaining records before deleting this record.",
  "settings.importExport.chooseResolution": "Choose resolution",
  "settings.importExport.applyAllSimilar": "Apply to all similar items",
  "settings.importExport.replaceRef": "Replacement Sakurava Ref",
  "settings.importExport.reviewGroup.credits": "Used by Credits",
  "settings.importExport.reviewGroup.category": "Category relationships",
  "settings.importExport.reviewGroup.glossary": "Glossary hierarchy",
  "settings.importExport.reviewGroup.dependencies": "Remaining dependencies",
  "settings.importExport.resolution.auto": "Auto",
  "settings.importExport.resolution.detach": "Detach",
  "settings.importExport.resolution.cascade": "Cascade",
  "settings.importExport.resolution.replace": "Replace",
  "settings.importExport.resolution.skip": "Skip",
  "settings.importExport.resolutionSummary": "{detach} detached, {replace} replaced, {cascade} added by cascade, {skip} skipped.",
  "settings.importExport.criticalAcknowledge": "I understand these destructive changes will be applied together after a verified safety backup.",
  "settings.importExport.reviewAgain": "Review Again",
  "settings.importExport.previewAgain": "Preview Again",
  "settings.importExport.showing": "Showing {start}–{end} of {total}",
  "settings.importExport.rowDetails": "Selected row details",
  "settings.importExport.rowNumber": "Row {row}",
  "settings.importExport.section.videos": "Videos",
  "settings.importExport.section.images": "Images",
  "settings.importExport.section.performers": "Performers",
  "settings.importExport.section.categories": "Categories",
  "settings.importExport.section.glossary": "Glossary",
  "settings.importExport.section.credits": "Credits",
  "settings.importExport.field.title": "Title",
  "settings.importExport.field.originalTitle": "Original Title",
  "settings.importExport.field.code": "Code",
  "settings.importExport.field.name": "Name",
  "settings.importExport.field.originalName": "Original Name",
  "settings.importExport.field.term": "Term",
  "settings.importExport.field.definition": "Definition",
  "settings.importExport.field.categoryName": "Category Name",
  "settings.importExport.field.categories": "Categories",
  "settings.importExport.field.relatedRecords": "Related records",
  "settings.importExport.field.favorite": "Favorite",
  "settings.importExport.field.availability": "Availability",
  "settings.importExport.field.censorship": "Censorship",
  "settings.importExport.field.releaseDate": "Release Date",
  "settings.importExport.field.birthDate": "Birth Date",
  "settings.importExport.field.debutDate": "Debut Date",
  "settings.importExport.field.retiredDate": "Retired Date",
  "settings.importExport.field.description": "Description",
  "settings.importExport.field.notes": "Notes",
  "settings.importExport.field.sourceLinks": "Source Links",
  "settings.importExport.of": "of",
  "settings.importExport.dataType": "Data type",
  "settings.importExport.format": "Format",
  "settings.importExport.exportMode": "Export catalog options",
  "settings.importExport.invalidDate": "{field}: Enter a valid date using this computer's format: {format}.",
  "settings.importExport.invalidWorkbook": "This XLSX workbook could not be read.",
  "settings.importExport.invalidSheet": "No supported Sakurava data worksheets were found.",
  "settings.importExport.preview": "Preview Before Apply",
  "settings.import.confirmApply": "Confirm Import",
  "settings.import.confirmApplyBody": "The reviewed changes will be applied to your catalog.",
  "settings.import.confirmApplySafety": "A verified safety backup will be created.",
  "settings.importExport.details.clearValue": "{field} will be cleared",
  "settings.import.confirmApplyDelete": "I understand that {count} records will be deleted.",
  "settings.import.confirmApplyAction": "Apply Import",
  "settings.import.confirmApplyAcknowledge": "I have reviewed the changes.",
  "settings.import.applyReport": "Import apply report",
  "settings.import.preview": "Import catalog preview",
  "settings.restore.confirm": "Confirm database restore",
  "settings.restore.replaceDatabase": "Current Sakurava database will be replaced.",
  "settings.restore.recordsOnly": "Only records are restored.",
  "settings.restore.mediaUnaffected": "Local media files are not restored or deleted.",
  "settings.cache.confirm": "Confirm cache cleanup",
  "settings.cache.scopedOnly": "Only scoped app-generated cache folders will be cleared.",
  "settings.cache.mediaUnaffected": "Source media files will not be deleted.",
  "settings.cache.catalogUnaffected": "SQLite records, categories, ratings, related links, and catalog data will not be changed.",
  "settings.categories.totalUnique": "Total unique categories",
  "settings.categories.usedVideos": "Categories used by Videos",
  "settings.categories.usedImages": "Categories used by Images",
  "settings.categories.usedPerformers": "Categories used by Performers",
  "settings.categories.total": "Total",
  "settings.categories.name": "Category name",
  "settings.categories.newName": "New category name",
  "settings.categories.renamePreview": "Record rename preview",
  "settings.categories.deletePreview": "Record delete preview",
  "settings.categories.affectedVideos": "Affected Videos",
  "settings.categories.affectedImages": "Affected Images",
  "settings.categories.affectedPerformers": "Affected Performers",
  "settings.categories.totalAffected": "Total affected records",
  "import.added": "Added",
  "import.modified": "Modified",
  "import.deleted": "Deleted",
  "import.unchanged": "Unchanged",
  "import.skipped": "Skipped",
  "import.failed": "Failed",
  "import.warnings": "Warnings",
  "import.errors": "Errors",
  "settings.performance.title": "Performance & Cache",
  "settings.performance.cacheSize": "Cache Size",
  "settings.performance.temporaryFiles": "Temporary Files",
  "picker.relatedPerformers.search": "Search related performers",
  "picker.relatedPerformers.placeholder":
    "Search performer name, alias, tag...",
  "picker.relatedPerformers.clear": "Clear related performer search",
  "picker.noRelatedPerformers": "No related performers selected.",
  "picker.rolePlaceholder": "Character or role name",
  "credit.empty": "No credits added.",
  "credit.add": "Add Credit",
  "credit.performer": "Performer",
  "credit.selectPerformer": "Select performer",
  "credit.characterMode": "Character Mode",
  "credit.text": "Text",
  "credit.self": "Self",
  "credit.characterRole": "Character / Role",
  "credit.characterOriginal": "Character Original Name",
  "credit.creditedAsMode": "Credited As Mode",
  "credit.auto": "Auto",
  "credit.custom": "Custom",
  "credit.creditedAs": "Credited As",
  "credit.roleImportance": "Role Importance",
  "credit.billingOrder": "Billing Order",
  "credit.note": "Note",
  "credit.notSet": "Not set",
  "categoryCard.thumbnailPlaceholder": "Category thumbnail placeholder",
  "categoryCard.noDescription": "No description yet.",
  "categoryCard.childCount": "{count} child category",
  "categoryCard.childrenCount": "{count} child categories",
  "categoryCard.childOf": "Child of {name}",
  "categoryCard.noParent": "No Parent Selected",
  "categoryCard.label": "Category {name}",
  "categoryManagement.title": "Category",
  "categoryManagement.name": "Category name",
  "categoryManagement.parent": "Parent Category",
  "categoryManagement.usedIn": "Used In",
  "categoryManagement.usedInControls": "Used In controls",
  "categoryManagement.thumbnail": "Thumbnail",
  "categoryManagement.thumbnailPlaceholder": "Local path or reference",
  "categoryManagement.definition": "Definition",
  "categoryManagement.definitionPlaceholder": "Plain text definition",
  "categoryManagement.toolbar": "Category toolbar",
  "categoryManagement.search": "Search categories",
  "categoryManagement.searchPlaceholder": "Search categories...",
  "categoryManagement.clearSearch": "Clear category search",
  "categoryManagement.filterOptions": "Category filter options",
  "categoryManagement.sortOptions": "Sort options",
  "categoryManagement.activeFilters": "Active category filters",
  "categoryManagement.pagination": "Category pagination",
  "categoryManagement.hierarchy": "Hierarchy",
  "categoryManagement.parentColumn": "Parent",
  "categoryManagement.usage": "Usage",
  "categoryManagement.totalUsage": "Total Usage",
  "categoryManagement.description": "Description",
  "categoryManagement.searchParent": "Search parent categories",
  "categoryManagement.searchParentPlaceholder": "Search parent categories...",
  "categoryManagement.clearParent": "Clear parent category search",
  "categoryManagement.subtitle": "Create, organize, and maintain catalog categories.",
  "categoryManagement.add": "Add Category",
  "categoryManagement.edit": "Edit Category",
  "categoryManagement.category": "Category",
  "categoryManagement.save": "Save Category",
  "categoryManagement.noParent": "No Parent Selected",
  "glossary.title": "Glossary Library",
  "glossary.subtitle": "Store and manage definitions, references, and terms for your personal use.",
  "glossary.addEntry": "Add Entry",
  "glossary.addForm": "Add Glossary Entry",
  "glossary.editForm": "Edit Glossary Entry",
  "glossary.saveEntry": "Save Entry",
  "glossary.sourceTitle": "Source Title",
  "glossary.markFavorite": "Mark this entry as favorite",
  "glossary.term": "Term",
  "glossary.termPlaceholder": "Enter term or title",
  "glossary.synonyms": "Synonyms",
  "glossary.synonymPlaceholder": "Add synonym and press Enter...",
  "glossary.addSynonym": "Add synonym",
  "glossary.sourceLabelPlaceholder":
    "e.g. Wikipedia, Official Website, Article",
  "glossary.parentPlaceholder": "Select parent term...",
  "glossary.sourceUrl": "Source URL",
  "glossary.sourceUrlPlaceholder": "https://example.com/reference-page",
  "glossary.imagePathPlaceholder": "/path/to/image.jpg",
  "glossary.definition": "Definition",
  "glossary.definitionPlaceholder":
    "Write the definition, explanation, or details about this term...",
  "glossary.toolbar": "Glossary toolbar",
  "glossary.search": "Search terms",
  "glossary.searchPlaceholder": "Search terms...",
  "glossary.clearSearch": "Clear glossary search",
  "glossary.activeFilters": "Glossary active filters",
  "glossary.pagination": "Glossary pagination",
  "glossary.synonymsColumn": "Synonyms",
  "glossary.categoriesColumn": "Categories",
  "glossary.sourceColumn": "Source",
  "glossary.favorite": "Favorite",
  "glossary.noParent": "No parent",
  "glossary.categoryOptions": "Category filter options",
  "migration.ref.title": "Upgrade catalog references",
  "migration.ref.body": "Sakurava will assign a permanent reference to {count} existing catalog records. Existing relationships will be preserved and no media files will be changed.",
  "migration.ref.safety": "A verified safety backup will be created first. Current CSV and XLSX exports will use Sakurava Ref.",
  "migration.ref.confirm": "Upgrade References",
  "migration.ref.pending": "Upgrading…",
  "migration.ref.precondition": "The catalog cannot be upgraded safely yet. Check the catalog and try again.",
  "migration.ref.failed": "The upgrade was cancelled. No catalog changes were applied.",
  "migration.ref.success": "Catalog references upgraded.",
  "migration.ref.recoveryTitle": "Catalog references need recovery",
  "migration.ref.recoveryBody": "Sakurava could not verify the catalog reference upgrade. Import and Export are unavailable until the catalog is recovered.",
  "migration.ref.retryValidation": "Retry Validation",
  "migration.ref.openRecovery": "Open Backup & Recovery",
  "migration.ref.validatingBody": "Sakurava is verifying that catalog references are ready.",
  "managedMedia.progress.preparing": "Preparing mini images — {ready} / {total} · {percentage}%",
  "managedMedia.progress.label": "Mini image preparation",
};

const indonesianDictionary: TranslationDictionary = {
  // Sidebar
  "app.sidebar.subtitle": "Katalog lokal pribadi",
  "app.sidebar.expand": "Perluas sidebar",
  "app.sidebar.collapse": "Ciutkan sidebar",
  "app.sidebar.navigateTo": "Buka {label}",
  "nav.home": "Beranda",
  "nav.videos": "Video",
  "nav.images": "Gambar",
  "nav.performers": "Performer",
  "nav.categories": "Kategori",
  "nav.glossary": "Glosarium",
  "nav.settings": "Pengaturan",

  // Settings
  "settings.title": "Pengaturan",
  "settings.description":
    "Kelola preferensi aplikasi, optimasi, keamanan data, dan informasi aplikasi.",
  "settings.resetToDefaults": "Atur Ulang ke Default",
  "settings.appearance.title": "Tampilan",
  "settings.appearance.description": "Sesuaikan tampilan dan nuansa Sakurava.",
  "settings.appearance.theme": "Tema",
  "settings.appearance.themeHelper": "Pilih tema aplikasi yang Anda inginkan.",
  "settings.appearance.light": "Terang",
  "settings.appearance.dark": "Gelap",
  "settings.appearance.accentStyle": "Gaya Aksen",
  "settings.appearance.accentStyleHelper": "Pilih warna aksen yang digunakan di seluruh aplikasi.",
  "settings.appearance.sakuraPinkSelected": "Sakura Pink dipilih",
  "settings.appearance.uiDensity": "Kepadatan UI",
  "settings.appearance.uiDensityHelper": "Kontrol ukuran elemen UI dan jarak.",
  "settings.appearance.compact": "Kompak",
  "settings.appearance.comfortable": "Nyaman",
  "settings.appearance.spacious": "Luas",
  "settings.language.title": "Bahasa",
  "settings.language.description":
    "Pilih bahasa aplikasi dan kelola paket bahasa kustom melalui CSV.",
  "settings.language.appLanguage": "Bahasa Aplikasi",
  "settings.language.appLanguageHelper": "Pilih bahasa yang digunakan di aplikasi.",
  "settings.language.catalogDataHelper":
    "Perubahan hanya berlaku untuk UI aplikasi. Data katalog tidak diterjemahkan.",
  "settings.language.installedLanguages": "Bahasa Terpasang",
  "settings.language.installedLanguagesHelper": "Kelola paket bahasa terpasang.",
  "settings.language.upToDate": "Terbaru",
  "settings.optimization.title": "Optimasi",
  "settings.optimization.description":
    "Kelola akses media, status cache, dan optimasi pustaka mendatang.",
  "settings.optimization.mediaLibrary": "Media & Pustaka",
  "settings.optimization.mediaLibraryHelper": "Kelola cara file media dimuat dan diproses.",
  "settings.optimization.addMediaRoot": "Tambah Root Media",
  "settings.optimization.addingMediaRoot": "Menambahkan Root Media...",
  "settings.optimization.cache": "Cache",
  "settings.optimization.cacheHelper": "Kelola file sementara yang digunakan untuk mempercepat aplikasi.",
  "settings.optimization.clearCache": "Hapus Cache",
  "settings.optimization.clearingCache": "Menghapus Cache...",
  "settings.optimization.catalogPreferences": "Preferensi Katalog",
  "settings.optimization.catalogPreferencesHelper": "Kontrol bagaimana data katalog Anda ditampilkan.",
  "settings.dataSafety.title": "Keamanan Data & Migrasi",
  "settings.dataSafety.description":
    "Cadangkan, pulihkan, impor, dan ekspor data dengan aman.",
  "settings.dataSafety.backupDatabase": "Cadangkan Database",
  "settings.dataSafety.backingUp": "Mencadangkan...",
  "settings.dataSafety.restoreDatabase": "Pulihkan Database",
  "settings.dataSafety.restoring": "Memulihkan...",
  "settings.dataSafety.importData": "Impor Data",
  "settings.dataSafety.exportData": "Ekspor Data",
  "settings.appInformation.title": "Informasi Aplikasi",
  "settings.appInformation.description":
    "Tinjau status runtime lokal, keamanan sistem, dan diagnostik.",
  "common.cancel": "Batal",
  "common.previous": "Sebelumnya",
  "common.next": "Berikutnya",
  "settings.backup.history.pageSize": "Ukuran halaman",
  "settings.importExport.title": "Impor / Ekspor",
  "settings.importExport.importCatalog": "Impor Katalog",
  "settings.importExport.exportCatalog": "Ekspor Katalog",
  "settings.importExport.changeFile": "Ganti File",
  "settings.importExport.needsReview": "Perlu Ditinjau",
  "settings.importExport.attention": "Perhatian",
  "settings.importExport.ready": "Siap",
  "settings.importExport.reading": "Membaca file katalog...",
  "settings.importExport.exporting": "Mengekspor...",
  "settings.importExport.filters": "Filter baris impor",
  "settings.importExport.filter.all": "Semua",
  "settings.importExport.filter.add": "Tambah",
  "settings.importExport.filter.create": "Buat",
  "settings.importExport.filter.update": "Perbarui",
  "settings.importExport.filter.delete": "Hapus",
  "settings.importExport.filter.skip": "Lewati",
  "settings.importExport.filter.error": "Perlu Ditinjau",
  "settings.importExport.filter.attention": "Perhatian",
  "settings.importExport.filter.warning": "Peringatan",
  "settings.importExport.searchRows": "Cari baris",
  "settings.importExport.table.row": "Baris",
  "settings.importExport.table.section": "Bagian",
  "settings.importExport.table.ref": "Sakurava Ref",
  "settings.importExport.table.record": "Catatan",
  "settings.importExport.table.action": "Aksi",
  "settings.importExport.table.details": "Rincian",
  "settings.importExport.table.status": "Status",
  "settings.importExport.generatedRef": "Sakurava Ref baru akan dibuat",
  "settings.importExport.selectSections": "Pilih bagian untuk diekspor",
  "settings.importExport.chooseFormat": "Pilih format ekspor",
  "settings.importExport.recommended": "Disarankan",
  "settings.importExport.compatibility": "Kompatibilitas",
  "settings.importExport.summary": "Ringkasan",
  "settings.importExport.sectionsSelected": "{count} bagian dipilih",
  "settings.importExport.formatSummary": "Format: {format}",
  "settings.importExport.exportAsTemplate": "Ekspor sebagai templat",
  "settings.importExport.templateLabel": "Templat",
  "settings.importExport.recordsSelected": "{count} catatan",
  "settings.importExport.emptySections": "Tidak ada catatan di {sections}. Aktifkan Ekspor sebagai templat untuk melanjutkan.",
  "settings.importExport.exportSelected": "Ekspor yang Dipilih",
  "settings.importExport.applyImport": "Terapkan Impor",
  "settings.importExport.noChanges": "Tidak Ada Perubahan",
  "settings.importExport.skipped": "Dilewati",
  "settings.importExport.rows": "baris",
  "settings.importExport.rowsNeedReview": "{count} baris perlu ditinjau.",
  "settings.importExport.itemsRequireDecision": "{count} item memerlukan keputusan.",
  "settings.importExport.reviewItems": "Tinjau {count} item",
  "settings.importExport.reviewResolutionHelp": "Pilih cara Sakurava mempertahankan catatan yang tersisa sebelum menghapus catatan ini.",
  "settings.importExport.chooseResolution": "Pilih penyelesaian",
  "settings.importExport.applyAllSimilar": "Terapkan ke semua item serupa",
  "settings.importExport.replaceRef": "Ref Sakurava pengganti",
  "settings.importExport.reviewGroup.credits": "Digunakan oleh Kredit",
  "settings.importExport.reviewGroup.category": "Relasi Kategori",
  "settings.importExport.reviewGroup.glossary": "Hierarki Glosarium",
  "settings.importExport.reviewGroup.dependencies": "Dependensi tersisa",
  "settings.importExport.resolution.auto": "Otomatis",
  "settings.importExport.resolution.detach": "Lepaskan",
  "settings.importExport.resolution.cascade": "Bertingkat",
  "settings.importExport.resolution.replace": "Ganti",
  "settings.importExport.resolution.skip": "Lewati",
  "settings.importExport.resolutionSummary": "{detach} dilepas, {replace} diganti, {cascade} ditambahkan melalui berantai, {skip} dilewati.",
  "settings.importExport.criticalAcknowledge": "Saya memahami perubahan destruktif ini akan diterapkan bersama setelah cadangan keamanan terverifikasi.",
  "settings.importExport.reviewAgain": "Tinjau Lagi",
  "settings.importExport.previewAgain": "Pratinjau Lagi",
  "settings.importExport.showing": "Menampilkan {start}–{end} dari {total}",
  "settings.importExport.rowDetails": "Rincian baris terpilih",
  "settings.importExport.rowNumber": "Baris {row}",
  "settings.importExport.section.videos": "Video",
  "settings.importExport.section.images": "Gambar",
  "settings.importExport.section.performers": "Performer",
  "settings.importExport.section.categories": "Kategori",
  "settings.importExport.section.glossary": "Glosarium",
  "settings.importExport.section.credits": "Kredit",
  "settings.importExport.exportMode": "Opsi ekspor katalog",
  "settings.importExport.details.create": "Catatan baru akan ditambahkan",
  "settings.importExport.details.delete": "Catatan akan dihapus",
  "settings.importExport.details.skip": "Baris akan dilewati",
  "settings.importExport.details.noChanges": "Tidak ada perubahan",
  "settings.importExport.details.review": "Tinjau baris ini",
  "settings.importExport.details.changeValue": "{field} berubah dari “{before}” menjadi “{after}”",
  "settings.importExport.details.updateField": "{field} akan diperbarui",
  "settings.importExport.details.updateFieldsNamed": "{count} bidang ({fields}) akan berubah",
  "settings.importExport.details.clearValue": "{field} akan dikosongkan",
  "settings.importExport.details.cleared": "Dikosongkan",
  "settings.importExport.details.valueWillBeCleared": "Nilai akan dikosongkan",
  "settings.importExport.details.invalidDate": "Tanggal tidak valid untuk komputer ini",
  "settings.importExport.details.idNotFound": "ID catatan tidak ditemukan",
  "settings.importExport.details.requiredMissing": "{field} wajib belum diisi",
  "settings.importExport.field.title": "Judul",
  "settings.importExport.field.originalTitle": "Judul Asli",
  "settings.importExport.field.code": "Kode",
  "settings.importExport.field.name": "Nama",
  "settings.importExport.field.originalName": "Nama Asli",
  "settings.importExport.field.term": "Istilah",
  "settings.importExport.field.definition": "Definisi",
  "settings.importExport.field.categoryName": "Nama Kategori",
  "settings.importExport.field.categories": "Kategori",
  "settings.importExport.field.relatedRecords": "Catatan terkait",
  "settings.importExport.field.favorite": "Favorit",
  "settings.importExport.field.availability": "Ketersediaan",
  "settings.importExport.field.censorship": "Sensor",
  "settings.importExport.field.releaseDate": "Tanggal Rilis",
  "settings.importExport.field.birthDate": "Tanggal Lahir",
  "settings.importExport.field.debutDate": "Tanggal Debut",
  "settings.importExport.field.retiredDate": "Tanggal Pensiun",
  "settings.importExport.field.description": "Deskripsi",
  "settings.importExport.field.notes": "Catatan",
  "settings.importExport.field.sourceLinks": "Tautan Sumber",
  "settings.import.confirmApply": "Konfirmasi Impor",
  "settings.import.confirmApplyBody": "Perubahan yang telah ditinjau akan diterapkan ke katalog Anda.",
  "settings.import.confirmApplySafety": "Cadangan keamanan terverifikasi akan dibuat.",
  "settings.import.confirmApplyDelete": "Saya memahami bahwa {count} catatan akan dihapus.",
  "settings.import.confirmApplyAction": "Terapkan Impor",
  "settings.import.confirmApplyAcknowledge": "Saya telah meninjau perubahan.",

  // Home
  "home.welcome": "Selamat Datang di Sakurava",
  "home.welcomeDescription":
    "Kelola katalog video, gambar, dan performer lokal Anda dalam satu aplikasi desktop pribadi.",
  "home.getStarted": "Mulai",
  "home.quickActions": "Aksi Cepat",
  "home.continueCataloging": "Lanjutkan Katalog",
  "home.recentlyAdded": "Baru Ditambahkan",
  "home.loadingCatalog": "Memuat item katalog...",
  "home.noRecordsYet": "Belum ada catatan.",
  "home.noRecentRecords":
    "Belum ada catatan terbaru. Video, Gambar, dan Performer akan muncul di sini setelah disimpan.",
  "home.summaryVideos": "Video",
  "home.summaryImages": "Gambar",
  "home.summaryPerformers": "Performer",
  "home.summaryFavorites": "Favorit",
  "home.addVideo": "Tambah Video",
  "home.addVideoDetail": "Buat item katalog video baru",
  "home.addImage": "Tambah Gambar",
  "home.addImageDetail": "Buat item katalog gambar baru",
  "home.addPerformer": "Tambah Performer",
  "home.addPerformerDetail": "Buat profil performer baru",

  // Collection chrome
  "collection.searchPlaceholder.videos": "Cari video...",
  "collection.searchPlaceholder.images": "Cari gambar...",
  "collection.searchPlaceholder.performers": "Cari performer...",
  "collection.title.videos": "Video",
  "collection.title.images": "Gambar",
  "collection.title.performers": "Performer",
  "collection.subtitle.videos": "Kelola katalog video lokal Anda",
  "collection.subtitle.images": "Kelola katalog gambar lokal Anda",
  "collection.subtitle.performers": "Kelola katalog performer lokal Anda",
  "collection.addVideo": "Tambah Video",
  "collection.addImage": "Tambah Gambar",
  "collection.addPerformer": "Tambah Performer",
  "collection.filter": "Filter",
  "collection.view": "Tampilan",
  "collection.switchToListView": "Beralih ke tampilan daftar",
  "collection.switchToGridView": "Beralih ke tampilan grid",
  "collection.sorting": "Urutan",
  "collection.categories": "Kategori",
  "collection.clearAllFilters": "Hapus semua filter",
  "collection.clearAll": "Hapus semua",
  "collection.categoryLimitReached": "Maksimal 5 filter kategori dapat aktif.",
  "collection.addCategoryFilter": "Tambah filter kategori",
  "collection.pageSize": "Ukuran halaman",
  "collection.perPage": "per halaman",
  "collection.previous": "Sebelumnya",
  "collection.next": "Berikutnya",
  "collection.noMatchingItems": "Tidak ada item yang cocok",
  "collection.noMatchingItemsHint": "Coba kata pencarian atau opsi urutan yang berbeda.",
  "collection.noSavedRecords": "Tidak ada catatan tersimpan",
  "collection.noSavedRecordsHint":
    "Kartu koleksi akan muncul di sini ketika item tersimpan tersedia.",
  "collection.itemsPerPage": "Item per halaman",
  "migration.ref.title": "Tingkatkan referensi katalog",
  "migration.ref.body": "Sakurava akan menetapkan referensi permanen untuk {count} catatan katalog yang ada. Relasi yang ada akan dipertahankan dan tidak ada berkas media yang diubah.",
  "migration.ref.safety": "Cadangan keamanan terverifikasi akan dibuat terlebih dahulu. Ekspor CSV dan XLSX saat ini akan menggunakan Sakurava Ref.",
  "migration.ref.confirm": "Tingkatkan Referensi",
  "migration.ref.pending": "Meningkatkan…",
  "migration.ref.precondition": "Katalog belum dapat ditingkatkan dengan aman. Periksa katalog lalu coba lagi.",
  "migration.ref.failed": "Peningkatan dibatalkan. Tidak ada perubahan katalog yang diterapkan.",
  "migration.ref.success": "Referensi katalog berhasil ditingkatkan.",
  "migration.ref.recoveryTitle": "Referensi katalog perlu dipulihkan",
  "migration.ref.recoveryBody": "Sakurava tidak dapat memverifikasi peningkatan referensi katalog. Impor dan Ekspor tidak tersedia sampai katalog dipulihkan.",
  "migration.ref.retryValidation": "Coba Validasi Lagi",
  "migration.ref.openRecovery": "Buka Pencadangan & Pemulihan",
  "migration.ref.validatingBody": "Sakurava sedang memverifikasi kesiapan referensi katalog.",
  "managedMedia.progress.preparing": "Menyiapkan gambar mini — {ready} / {total} · {percentage}%",
  "managedMedia.progress.label": "Persiapan gambar mini",
};

const dictionaries: Record<LanguageCode, TranslationDictionary> = {
  en: englishDictionary,
};

export function getAllTranslationKeys(): string[] {
  const keySet = new Set<string>();
  for (const dictionary of Object.values(dictionaries)) {
    for (const key of Object.keys(dictionary)) {
      keySet.add(key);
    }
  }
  const preferredPrefixes = [
    "common.",
    "home.",
    "sidebar.",
    "app.sidebar.",
    "catalog.",
    "collection.",
    "detail.",
    "form.",
    "categories.",
    "categoryManagement.",
    "glossary.",
    "settings.",
    "viewer.",
  ];
  const rank = (key: string) => {
    const index = preferredPrefixes.findIndex((prefix) => key.startsWith(prefix));
    return index === -1 ? preferredPrefixes.length : index;
  };
  return [...keySet].sort(
    (left, right) =>
      rank(left) - rank(right) || left.localeCompare(right),
  );
}

export function getBuiltInText(
  languageCode: LanguageCode,
  key: string,
): string | undefined {
  const normalizedLanguage =
    typeof languageCode === "string"
      ? languageCode.trim().toLowerCase()
      : defaultLanguageCode;
  const dict = dictionaries[normalizedLanguage];
  return dict?.[key];
}

export function getKeyDescription(key: string): string {
  const explicitContexts: Record<string, string> = {
    "categories.table.header.name": "Categories > Table > Header > Name",
    "categories.table.header.description": "Categories > Table > Header > Description",
    "categories.table.header.parent": "Categories > Table > Header > Parent",
    "categories.table.header.usage": "Categories > Table > Header > Usage",
    "categories.table.header.totalUsage": "Categories > Table > Header > Total Usage",
    "glossary.form.field.category": "Glossary > Form > Field > Category",
    "glossary.form.field.thumbnail": "Glossary > Form > Field > Thumbnail",
    "common.status.available": "Common > Status Value > Available",
    "common.value.notAvailable": "Common > Value > Not Available",
    "detail.performer.yearsActive.duration":
      "Detail > Performer > Featured > Years Active Duration",
  };
  if (explicitContexts[key]) {
    return explicitContexts[key];
  }
  if (key.startsWith("common.count.")) {
    const label = key.slice("common.count.".length)
      .replace(/([a-z])([A-Z])/g, "$1 $2")
      .replace(/^./, (letter) => letter.toUpperCase());
    return `Common > Count Template > ${label}`;
  }
  if (key.startsWith("catalog.filterChip.")) {
    const contextLabels: Record<string, string> = {
      category: "Category",
      availability: "Availability",
      censorship: "Censorship",
      releaseYears: "Release Years",
      publisherLabel: "Publisher/Label",
      quality: "Quality",
      rating: "Rating",
      duration: "Duration",
      imageCount: "Image Count",
      cupSize: "Cup Size",
      gender: "Gender",
      bodyHeight: "Body Height",
      age: "Age",
      bodyType: "Body Type",
      nationality: "Nationality",
      debutYears: "Debut Years",
      filmographyCount: "Filmography Count",
      pictorialsCount: "Pictorials Count",
    };
    const suffix = key.slice("catalog.filterChip.".length);
    return `Catalog > Toolbar > Active Filter Chip > ${contextLabels[suffix] ?? suffix}`;
  }
  const labels: Record<string, string> = {
    app: "App",
    ui: "UI",
    csv: "CSV",
    id: "ID",
    viewer: "Image Viewer",
  };
  return key
    .split(".")
    .map((part) => labels[part] ?? part.replace(/([a-z])([A-Z])/g, "$1 $2")
      .replace(/^./, (letter) => letter.toUpperCase()))
    .join(" > ");
}

export function normalizeLanguageCode(value: unknown): LanguageCode {
  return resolveAvailableLanguageCode(value) ?? defaultLanguageCode;
}

export function resolveAvailableLanguageCode(
  value: unknown,
  storage: TranslationStorage | null = browserStorage(),
): LanguageCode | null {
  const identity = normalizeLanguageIdentity(value);
  if (!identity) return null;
  if (identity === defaultLanguageCode) return defaultLanguageCode;
  if (!storage) return null;
  const inspection = inspectStoredCustomLanguages(storage);
  if (
    inspection.classification === "fatal" ||
    inspection.classification === "ambiguous" ||
    inspection.classification === "transaction_recovery_required" ||
    inspection.ambiguousIdentities.includes(identity)
  ) {
    return null;
  }
  return inspection.languages.some(
    (language) => normalizeLanguageIdentity(language.code) === identity,
  ) ? identity : null;
}

export function getStoredLanguageCode(
  storage: TranslationStorage | null = browserStorage(),
): LanguageCode {
  if (!storage) return defaultLanguageCode;
  const read = readRawTranslationSnapshot(storage);
  if (!read.ok || read.snapshot.journal !== null) return defaultLanguageCode;
  const raw = read.snapshot.state[languageStorageKey];
  return resolveAvailableLanguageCode(raw, storage) ?? defaultLanguageCode;
}

export type LanguageSelectionMutationResult =
  | { readonly ok: true; readonly status: "committed" | "unchanged" }
  | {
      readonly ok: false;
      readonly status: "storage_unavailable" | "unknown_language" | "unsafe_stored_state" | "stale_snapshot" | "storage_failure" | "transaction_recovery_required";
      readonly error: string;
      readonly recoveryRequired?: boolean;
    };

export function storeLanguageCode(
  languageCode: LanguageCode,
  storage: TranslationStorage | null = browserStorage(),
): LanguageSelectionMutationResult {
  if (!storage) {
    return { ok: false, status: "storage_unavailable", error: "Language selection requires browser storage." };
  }
  const resolved = resolveAvailableLanguageCode(languageCode, storage);
  if (!resolved) {
    return { ok: false, status: "unknown_language", error: "The selected language is not installed or has an ambiguous identity." };
  }
  const customInspection = inspectStoredCustomLanguages(storage);
  if (customInspection.classification === "fatal" || customInspection.classification === "ambiguous" || customInspection.classification === "transaction_recovery_required") {
    return {
      ok: false,
      status: customInspection.classification === "transaction_recovery_required" ? "transaction_recovery_required" : "unsafe_stored_state",
      error: "Translation storage must be resolved before language selection can be changed.",
      recoveryRequired: customInspection.classification === "transaction_recovery_required",
    };
  }
  const snapshot = customInspection.snapshot;
  if (!snapshot) return { ok: false, status: "storage_failure", error: "Translation storage could not be read." };
  const currentEffective = resolveAvailableLanguageCode(
    snapshot.state[languageStorageKey],
    storage,
  ) ?? defaultLanguageCode;
  if (currentEffective === resolved) {
    return { ok: true, status: "unchanged" };
  }
  const plan = createTranslationTransactionPlan(snapshot, `language-selection:${resolved}`, {
    [languageStorageKey]: languageCode,
  });
  if (!plan.ok) return { ok: false, status: "storage_failure", error: `Language-selection transaction plan failed: ${plan.code}.` };
  const committed = commitTranslationTransaction(storage, plan.plan);
  if (committed.ok) return { ok: true, status: "committed" };
  if (committed.status === "stale_snapshot") {
    return { ok: false, status: "stale_snapshot", error: "Translation storage changed before the language selection could be committed." };
  }
  const recoveryRequired = committed.status === "transaction_recovery_required";
  return {
    ok: false,
    status: recoveryRequired ? "transaction_recovery_required" : "storage_failure",
    error: recoveryRequired ? "Translation storage requires explicit transaction recovery." : "Language selection could not be persisted.",
    recoveryRequired,
  };
}

export function translate(
  languageCode: LanguageCode,
  key: string,
  replacements: Record<string, string> = {},
  overrides: Partial<Record<string, string>> = {},
  englishOverrides: Partial<Record<string, string>> = {},
) {
  // Translation runs for every visible label. Selection is validated when it
  // enters LanguageContext, so avoid reparsing custom-language localStorage on
  // every t() call.
  const normalizedLanguage = normalizeLanguageIdentity(languageCode) ?? defaultLanguageCode;
  const translated =
    overrides[key] ??
    (normalizedLanguage === defaultLanguageCode ? undefined : englishOverrides[key]) ??
    dictionaries[defaultLanguageCode][key] ??
    key;

  const replacementEntries = Object.entries(replacements);
  if (replacementEntries.length === 0) {
    return translated;
  }

  return replacementEntries.reduce(
    (text, [replacementKey, replacementValue]) =>
      text.split(`{${replacementKey}}`).join(replacementValue),
    translated,
  );
}
